# -*- coding: utf-8 -*-
"""CifraDeCesar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lnw3htu-D2M0xBb46pHSUt3ODwkXZ9oz
"""

def decrypt(text,s):
  result = ""

  for i in range(len(text)):
    char = text[i]

    if (char.isupper()):
      result += chr((ord(char) - s-65) % 26 + 65)

    else:
      result += chr((ord(char) - s - 97) % 26 + 97)

  return result

